# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OBDdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(null=True)),
                ('vss', models.FloatField(null=True)),
                ('maf', models.FloatField(null=True)),
                ('rpm', models.FloatField(null=True)),
                ('kpl', models.FloatField(null=True)),
                ('coolant_temp', models.FloatField(null=True)),
                ('oil_temp', models.FloatField(null=True)),
                ('control_module_voltage', models.FloatField(null=True)),
                ('intake_temp', models.FloatField(null=True)),
                ('speed', models.FloatField(null=True)),
                ('intake_pressure', models.FloatField(null=True)),
            ],
        ),
    ]
