# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readOBD', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obddb',
            name='time',
        ),
        migrations.AddField(
            model_name='obddb',
            name='local_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
